# Generated by Django 4.2.7 on 2024-03-04 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_saved_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(blank=True, related_name="following_users", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(blank=True, related_name="follower_users", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name="user",
            name="blocked_accounts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="close_friends",
        ),
        migrations.RemoveField(
            model_name="user",
            name="muted_accounts",
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_accounts",
            field=models.ManyToManyField(blank=True, related_name="blocking", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="close_friends",
            field=models.ManyToManyField(blank=True, related_name="friends_of", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="muted_accounts",
            field=models.ManyToManyField(blank=True, related_name="muting", to=settings.AUTH_USER_MODEL),
        ),
    ]
