# Generated by Django 4.2.7 on 2024-03-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="file",
            field=models.FileField(null=True, upload_to="story/"),
        ),
    ]
